---
_cp_install_script_url: https://get.rke2.io
_cp_packages: []
_cp_config_dir: /etc/rancher/rke2
_cp_config_file: /etc/rancher/rke2/config.yaml
_cp_kubeconfig_path: /etc/rancher/rke2/rke2.yaml
_cp_service_name: rke2-server
_cp_service_name_agent: rke2-agent
_cp_binary: /usr/local/bin/rke2
_cp_kubectl_cmd: /var/lib/rancher/rke2/bin/kubectl
_cp_rhsm_required: false
_cp_has_builtin_registry: false
_cp_has_builtin_ingress: true
_cp_builtin_ingress_name: rke2-ingress-nginx
_cp_firewall_ports:
  - 6443/tcp
  - 9345/tcp
  - 10250/tcp
  - 8472/udp
  - 4789/udp
  - 2379/tcp
  - 2380/tcp
