---
- name: gitlab_ce - restart gitlab
  ansible.builtin.command:
    cmd: gitlab-ctl restart
  become: true
  listen: gitlab_ce - restart gitlab
  changed_when: true

- name: gitlab_ce - reconfigure
  ansible.builtin.command:
    cmd: gitlab-ctl reconfigure
  become: true
  listen: gitlab_ce - reconfigure
  changed_when: true
