---

# Variables for the satellite kickstart

ks_path: "ks.cfg"                        # noqa var-naming[no-role-prefix]
oem_dir: "/run/media/ansiblerunner/OEMDRV"    # noqa var-naming[no-role-prefix]

baremetal_hosts:                         # noqa var-naming[no-role-prefix]
  - rhis_role: "satellite"
    hostname: "satellite"
    domain: "example.ca"
    mac: "94:c6:91:a6:2a:89"
    ipv4_address: "192.168.140.12"
    ipv4_netmask: "255.255.252.0"
    ipv4_gateway: "192.168.140.1"
    name_server1: "192.168.140.5"
    name_server2: "192.168.252.6"
    root_enc_pass: "{{ encrypted_root_pass_vault }}"
    grub_enc_pass: "{{ encrypted_grub_pass_vault }}"
    boot_disk: "nvme0n1"
    root_disk: "nvme0n1"
#    additional_disks:
#      - "/dev/sda"
    # We will always use compliance layout
    boot_mb: 1024
    boot_efi_mb: 2048
    lv_root_mb: 65536
    lv_home_mb: 20480
    lv_tmp_mb: 6144
    lv_var_tmp_mb: 6144
    lv_var_log_mb: 6144
    lv_var_log_audit_mb: 6144
    lv_var_mb: 1
    username: "ansiblerunner"
    user_enc_pass: "{{ encrypted_user_pass_vault }}"
    user_sudoer_policy: "{{ user_sudoer_policy_vault }}"
    ssh_pub_key: "{{ ssh_pub_key_vault }}"
    org: "{{ cdn_organization_vault }}"
    activation_key: "{{ cdn_activation_key_vault }}"
