---
- name: ingress_traefik - restart ingress
  kubernetes.core.k8s:
    kubeconfig: "{{ cp_kubeconfig_path | default('/etc/rancher/k3s/k3s.yaml') }}"
    api_version: apps/v1
    kind: Deployment
    name: traefik
    namespace: "{{ 'kube-system' if cp_type | default('k3s') == 'k3s' else 'traefik' }}"
    definition:
      spec:
        template:
          metadata:
            annotations:
              kubectl.kubernetes.io/restartedAt: "{{ ansible_date_time.iso8601 }}"
  listen: ingress_traefik - restart ingress
